# -*- coding: utf-8 -*-
"""trabalhoM1_campoMinado.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2rxTQMZQN1EV_0DyyOJFNiUflEoCt_H
"""

valida_looping = True
NUM_MINAS = 15
gabarito = [
  [1,1,1,"-","-",2,"*",2,"-"],
  [2,"*",2,1,1,2,"*",2,"-"],
  ["*",2,2,"*",1,1,1,2,1],
  [1,1,2,2,2,1,1,2,"*"],
  ["-","-",1,"*",2,2,"*",2,1],
  ["-","-",2,2,3,"*",2,1,"-"],
  [1,2,3,"*",2,1,1,"-","-"],
  [2,"*","*",2,1,1,2,2,1],
  ["*",3,2,1,"-",1,"*","*",1]        
]

campo_minado = [
  ["#","#","#","#","#","#","#","#","#"],
  ["#","#","#","#","#","#","#","#","#"],
  ["#","#","#","#","#","#","#","#","#"],
  ["#","#","#","#","#","#","#","#","#"],
  ["#","#","#","#","#","#","#","#","#"],
  ["#","#","#","#","#","#","#","#","#"],
  ["#","#","#","#","#","#","#","#","#"],
  ["#","#","#","#","#","#","#","#","#"],
  ["#","#","#","#","#","#","#","#","#"],           
]

def atualiza_campoMinado():
  for linha in range(len(campo_minado)):
    for coluna in range(len(campo_minado[linha])):
       valor = campo_minado[linha][coluna]
       print(valor, end='')
    print("")

def enviaValor(linha,coluna):
  if campo_minado[linha][coluna] == "#":
    if gabarito[linha][coluna] == "*":
      campo_minado[linha][coluna] = gabarito[linha][coluna]
      atualiza_campoMinado()
      print("BOOM!!!")
      print("---------")
      print("GAME OVER")
      print("---------")
      return False
    elif gabarito[linha][coluna] ==1 or gabarito[linha][coluna] ==2 or gabarito[linha][coluna] ==3 or gabarito[linha][coluna] == 4:
      campo_minado[linha][coluna] = gabarito[linha][coluna]
      return True
    elif gabarito[linha][coluna] == "-":
      if linha == 0:
        if coluna == 0:
          campo_minado[linha][coluna] = gabarito[linha][coluna]
          campo_minado[linha][coluna + 1] = gabarito[linha][coluna + 1]
          campo_minado[linha + 1][coluna + 1] = gabarito[linha + 1][coluna + 1]
          campo_minado[linha + 1][coluna] = gabarito[linha + 1][coluna]
        elif coluna == 8:
          campo_minado[linha][coluna] = gabarito[linha][coluna]
          campo_minado[linha + 1][coluna] = gabarito[linha + 1][coluna]
          campo_minado[linha + 1][coluna - 1] = gabarito[linha + 1][coluna - 1]
          campo_minado[linha][coluna - 1] = gabarito[linha][coluna - 1]
        else:
          campo_minado[linha][coluna] = gabarito[linha][coluna]
          campo_minado[linha][coluna - 1] = gabarito[linha][coluna - 1]
          campo_minado[linha][coluna + 1] = gabarito[linha][coluna + 1]
          campo_minado[linha + 1][coluna + 1] = gabarito[linha + 1][coluna + 1]
          campo_minado[linha + 1][coluna] = gabarito[linha + 1][coluna]
          campo_minado[linha +1][coluna - 1] = gabarito[linha +1][coluna - 1] 
      elif linha == 8:
        if coluna == 0:
          campo_minado[linha][coluna] = gabarito[linha][coluna]
          campo_minado[linha - 1][coluna] = gabarito[linha - 1][coluna]
          campo_minado[linha - 1][coluna + 1] = gabarito[linha - 1][coluna + 1]
          campo_minado[linha][coluna + 1] = gabarito[linha][coluna + 1]
        elif coluna == 8:
          campo_minado[linha][coluna] = gabarito[linha][coluna]
          campo_minado[linha - 1][coluna] = gabarito[linha - 1][coluna]
          campo_minado[linha][coluna - 1] = gabarito[linha][coluna - 1]
          campo_minado[linha - 1][coluna - 1] = gabarito[linha - 1][coluna - 1] 
        else:
          campo_minado[linha][coluna] = gabarito[linha][coluna]
          campo_minado[linha][coluna - 1] = gabarito[linha][coluna - 1]
          campo_minado[linha - 1][coluna - 1] = gabarito[linha - 1][coluna - 1]
          campo_minado[linha - 1][coluna] = gabarito[linha - 1][coluna]
          campo_minado[linha - 1][coluna + 1] = gabarito[linha - 1][coluna + 1] 
          campo_minado[linha][coluna + 1] = gabarito[linha][coluna + 1]
      elif coluna == 0:
        if linha == 0:
          campo_minado[linha][coluna] = gabarito[linha][coluna]
          campo_minado[linha][coluna + 1] = gabarito[linha][coluna + 1]
          campo_minado[linha + 1][coluna + 1] = gabarito[linha + 1][coluna + 1]
          campo_minado[linha + 1][coluna] = gabarito[linha + 1][coluna]
        elif linha == 8:                
          campo_minado[linha][coluna] = gabarito[linha][coluna]
          campo_minado[linha - 1][coluna] = gabarito[linha - 1][coluna]
          campo_minado[linha - 1][coluna + 1] = gabarito[linha - 1][coluna + 1]
          campo_minado[linha][coluna + 1] = gabarito[linha][coluna + 1]
        else:
          campo_minado[linha][coluna] = gabarito[linha][coluna]
          campo_minado[linha - 1][coluna] = gabarito[linha - 1][coluna]
          campo_minado[linha - 1][coluna + 1] = gabarito[linha - 1][coluna + 1]
          campo_minado[linha][coluna + 1] = gabarito[linha][coluna + 1]
          campo_minado[linha + 1][coluna + 1] = gabarito[linha + 1][coluna + 1]
          campo_minado[linha + 1][coluna] = gabarito[linha + 1][coluna]
      elif coluna == 8:
        if linha == 0:
          campo_minado[linha][coluna] = gabarito[linha][coluna]
          campo_minado[linha + 1][coluna] = gabarito[linha + 1][coluna]
          campo_minado[linha + 1][coluna - 1] = gabarito[linha + 1][coluna - 1]
          campo_minado[linha][coluna - 1] = gabarito[linha][coluna - 1]      
        if linha == 8:
          campo_minado[linha][coluna] = gabarito[linha][coluna]
          campo_minado[linha - 1][coluna] = gabarito[linha - 1][coluna]
          campo_minado[linha][coluna - 1] = gabarito[linha][coluna - 1]
          campo_minado[linha - 1][coluna - 1] = gabarito[linha - 1][coluna - 1] 
        else:    
          campo_minado[linha][coluna] = gabarito[linha][coluna]
          campo_minado[linha + 1][coluna] = gabarito[linha + 1][coluna]
          campo_minado[linha + 1][coluna - 1] = gabarito[linha + 1][coluna - 1]
          campo_minado[linha][coluna -1] = gabarito[linha][coluna -1]
          campo_minado[linha - 1][coluna] = gabarito[linha - 1][coluna]
          campo_minado[linha - 1][coluna - 1] = gabarito[linha - 1][coluna - 1]
      else:    
        campo_minado[linha][coluna] = gabarito[linha][coluna]
        campo_minado[linha - 1][coluna]  = gabarito[linha - 1][coluna] 
        campo_minado[linha - 1][coluna + 1] = gabarito[linha - 1][coluna + 1]
        campo_minado[linha][coluna + 1] = gabarito[linha][coluna + 1]
        campo_minado[linha + 1][coluna + 1] = gabarito[linha + 1][coluna + 1]
        campo_minado[linha + 1][coluna] = gabarito[linha + 1][coluna] 
        campo_minado[linha + 1][coluna - 1] = gabarito[linha + 1][coluna - 1]
        campo_minado[linha][coluna - 1] = gabarito[linha][coluna - 1]
        campo_minado[linha - 1][coluna - 1] = gabarito[linha - 1][coluna - 1]
    return True    
  else:
    print("Valor já escolhido! Tente novamente!") 
    return True

def verifica_vencedor():
  contador = 0
  for linha in range(len(campo_minado)):
    for coluna in range(len(campo_minado[linha])):
      if(campo_minado[linha][coluna] == "#"):
        contador = contador + 1
  if(contador == NUM_MINAS):
    print("PARABÉNSSS, VOCÊ GANHOU O JOGO")
    return False
  else:
    return True



print("--------------------------")
print("     CAMPO MINADO         ")
print("--------------------------")
print("~Ecolha posições de 0 a 8~")    
while(valida_looping): 
  #print('\n'*100)
  valida_looping = verifica_vencedor()   
  atualiza_campoMinado()
  linha = int(input("linha:"))
  coluna = int(input("coluna:")) 
  valida_looping = enviaValor(linha,coluna)

